services:
  postgres:
    container_name: sosavpn_postgres 
    image: postgres:latest 
    restart: unless-stopped
    environment:
      POSTGRES_USER: sosapostres
      POSTGRES_PASSWORD: raufartem777
      POSTGRES_DB: postgres 
      PGDATA: /var/lib/postgresql/data 
    volumes:
       - postgres_data:/var/lib/postgresql/data 
    networks:
      - remnawave-network 

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: artyomborisov11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: raufartem777
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/var/lib/pgadmin 
    ports:
      - "${PGADMIN_PORT}:80" 
    networks:
      - remnawave-network 
    depends_on:
      - postgres 


