services:
  bot:
    container_name: sosavpn_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - remnawave-network

  redis:
    image: redis:latest
    container_name: sosavpn_redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    command: >
      sh -c '
        # Создаем директорию для конфигов
        mkdir -p /usr/local/etc/redis &&
        # Базовая конфигурация Redis
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        
        # Создаем файл ACL
        # user default on nopass ~* +@all - если default не нужен с паролем
        # Важно: $REDIS_USER и $REDIS_USER_PASSWORD подставятся из .env файла compose
        echo "user ${REDIS_USER} on >${REDIS_USER_PASSWORD} ~* +@all" > /usr/local/etc/redis/users.acl &&
        
        # Запускаем Redis с ACL файлом
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "redis://${REDIS_USER}:${REDIS_USER_PASSWORD}@localhost:6379", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - remnawave-network 
    tty: true
    stdin_open: true

  postgres:
    container_name: sosavpn_postgres 
    image: postgres:latest 
    restart: unless-stopped
    environment:
      POSTGRES_USER: sosapostres
      POSTGRES_PASSWORD: raufartem777
      POSTGRES_DB: postgres 
      PGDATA: /var/lib/postgresql/data 
    volumes:
       - postgres_data:/var/lib/postgresql/data 
    networks:
      - remnawave-network 

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: artyomborisov11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: raufartem777
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/var/lib/pgadmin 
    ports:
      - "${PGADMIN_PORT}:80" 
    networks:
      - remnawave-network 
    depends_on:
      - postgres 

networks:
  remnawave-network:
    external: true

volumes:
  postgres_data: 
  redis_data:    
  pgadmin_data:  

